blank_issues_enabled: true
contact_links:
  - name: Leitfaden zum Erstellen eines Bug-Reports
    url:  https://github.com/stewie42/Rack/blob/master/documentation/Leitfaden.md
    about: Alles wissenswertes über das Erstellen eines Bug-Reports
